version: '3.8'

services:
  yandexart:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
    restart: unless-stopped
    env_file:
      - .env 